services:
  paper:
    image: itzg/minecraft-server:java23
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: TRUE
      TYPE: PURPUR
      VERSION: 1.20.1
      MEMORY: 2560M
      MAX_PLAYERS: 70
      MOTD: Oyasai Server
      ICON: https://avatars.githubusercontent.com/u/70241145
      OVERRIDE_ICON: true
      USE_AIKAR_FLAGS: true
      TZ: Asia/Tokyo
      DIFFICULTY: 2
      PVP: false
      FORCE_GAMEMODE: true
      ENABLE_COMMAND_BLOCK: true
      SPAWN_ANIMALS: false
      SPAWN_MONSTERS: false
      SPAWN_NPCS: false
      ENTITY_BROADCAST_RANGE_PERCENTAGE: 80
      SIMULATION_DISTANCE: 12
      VIEW_DISTANCE: 12
      LEVEL: main
      GENERATE_STRUCTURES: false
      SPAWN_PROTECTION: 0
      MAX_TICK_TIME: -1
      MAX_CHAINED_NEIGHBOR_UPDATES: 500000
      OPS: |-
        eru__chan
      PLUGINS: |-
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.luckperms.net/1575/bukkit/loader/LuckPerms-Bukkit-5.4.158.jar
        https://jitpack.io/com/github/Realizedd/TokenManager/3.2.4/TokenManager-3.2.4.jar
        https://maven.playpro.com/net/coreprotect/coreprotect/22.4/coreprotect-22.4.jar
        https://repo.extendedclip.com/releases/me/clip/placeholderapi/2.11.6/placeholderapi-2.11.6.jar
        https://dev.bukkit.org/projects/worldguard/files/4675318/download
        https://github.com/DevLeoko/AdvancedBan/releases/download/v2.3.0/AdvancedBan-Bundle-2.3.0-RELEASE.jar
        https://github.com/ViaVersion/ViaVersion/releases/download/5.3.2/ViaVersion-5.3.2.jar
        https://github.com/Test-Account666/PlugManX/releases/download/2.4.1/PlugManX-2.4.1.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.21.0/EssentialsX-2.21.0.jar
        https://github.com/K0bus/CreativeManager/releases/download/1.21/CreativeManager-1.21.jar
        https://github.com/IntellectualSites/FastAsyncWorldEdit/releases/download/2.12.2/FastAsyncWorldEdit-Bukkit-2.12.2.jar
        https://github.com/gecolay/GSit/releases/download/2.3.1/GSit-2.3.1.jar
        https://github.com/Multiverse/Multiverse-Core/releases/download/4.3.16/multiverse-core-4.3.16.jar
        https://github.com/Multiverse/Multiverse-Portals/releases/download/4.2.3/multiverse-portals-4.2.3.jar
        https://github.com/dmulloy2/ProtocolLib/releases/download/5.3.0/ProtocolLib.jar
        https://github.com/NEZNAMY/TAB/releases/download/5.2.0/TAB.v5.2.0.jar
        https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar
        https://github.com/2008Choco/VeinMiner/releases/download/v2.2.6/VeinMiner-Bukkit-2.2.6.jar
        https://github.com/NuVotifier/NuVotifier/releases/download/v2.7.3/nuvotifier.jar
        https://github.com/KevinDaGame/VoxelSniper-Reimagined/releases/download/v8.14.0/voxelsniper-8.14.0-spigot.jar
        https://github.com/kennytv/WorldEditSUI/releases/download/1.7.4/WorldEditSUI-1.7.4.jar
      NETWORK_COMPRESSION_THRESHOLD: 512
      PAUSE_WHEN_EMPTY_SECONDS: 30
      PLAYER_IDLE_TIMEOUT: 6000
      ENABLE_ROLLING_LOGS: true
      LOG_TIMESTAMP: true
    volumes:
      - ./data:/data
